<a href="https://colab.research.google.com/github/samibahig/IFT6390/blob/main/LogisticRegression%2CRandomForestClassifier%2C_BaggingClassifier%2C_AdaBoostClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier
from sklearn.svm import SVC

In [ ]:
from sklearn.linear_model import LogisticRegressionCV

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
from sklearn import svm

In [ ]:
train_ds, test_ds = np.load('/content/train.npz'), np.load('/content/test.npz')

In [ ]:
X = train_ds['arr_0']
Y = train_ds['arr_1']

In [ ]:
X_normalized = X/255

In [ ]:
X.shape, Y.shape

((1500, 784), (1500,))

In [ ]:
len(X)

1500

In [ ]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(Y)

[4 5 5 ... 0 2 4]


In [ ]:
X_test = test_ds['arr_0']

In [ ]:
X_normalized.shape

(1500, 784)

In [ ]:
print(X_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
X_train, X_valid, Y_train, Y_valid = train_test_split(X, Y, train_size=0.8, test_size=0.2, random_state=35)

In [ ]:
X_normalized = preprocessing.normalize(X_train, norm='l2')

In [ ]:
#svc = SVC(C=1.0, kernel='poly', degree=6, gamma=10, coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200)

In [ ]:
clf = LogisticRegressionCV(Cs=10, penalty='l2', dual=False, tol=0.0001, fit_intercept=True, intercept_scaling=1, random_state=42, max_iter=200)
#svc.fit(xtrain, ytrain)

In [ ]:
LR = LogisticRegressionCV()
LRparam_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    'penalty': ['l1', 'l2'],
    'max_iter': list(range(100,800,100)),
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}
LR_search = GridSearchCV(LR, param_grid=LRparam_grid, refit = True, verbose = 3, cv=5)

# fitting the model for grid search 
LR_search.fit(X_train, Y_train)
LR_search.best_params_
# summarize
print('Mean Accuracy: %.3f' % LR_search.best_score_)
print('Config: %s' % LR_search.best_params_)

Fitting 5 folds for each of 490 candidates, totalling 2450 fits
[CV] C=0.001, max_iter=100, penalty=l1, solver=newton-cg .............


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


ValueError: ignored

In [ ]:
clf.fit(X, Y)

ValueError: ignored

In [ ]:
clf.fit(X_train, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
                     fit_intercept=True, intercept_scaling=1, l1_ratios=None,
                     max_iter=200, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=42, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
dt.score(X_valid, Y_valid)

NameError: ignored

In [ ]:
#clf = BaggingClassifier(base_estimator=RandomForestClassifier(),  n_estimators=10, random_state=42).fit(X_train, Y_train)
#clf = AdaBoostClassifier(DecisionTreeClassifier(), n_estimators = 5, learning_rate = 1) 
clf = AdaBoostClassifier(base_estimator= DecisionTreeClassifier(), n_estimators=2000, learning_rate = 4.0, random_state = 123)
clf.fit(X_train, Y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                       

In [ ]:
clf.score(X_valid, Y_valid)

0.2833333333333333

In [ ]:
pred = clf.predict(X_test)

In [ ]:
df = pd.DataFrame(pred)

In [ ]:
df.to_csv('Regression logistique',index=True, index_label='Id', header=['Category'])